### ISSUE TITLE
Not running on nested files for `**/*.js`

### ISSUE THREAD

**Issue by mydea** [machty/ember-concurrency-codemods#1]
Hi, thanks for the great codemod. However, I noticed it does not seem to run properly with a glob pattern. 

I ran this command: 

```
> npx machty-ember-concurrency-codemods async-arrow-task **/*.js **/*.ts
Processing 7 files... 
Spawning 7 workers...
Sending 1 files to free worker...
Sending 1 files to free worker...
Sending 1 files to free worker...
Sending 1 files to free worker...
Sending 1 files to free worker...
Sending 1 files to free worker...
Sending 1 files to free worker...
All done. 
Results: 
0 errors
7 unmodified
0 skipped
0 ok
```

Then, I ran this command, because I knew there was a file using ec:

```
> npx machty-ember-concurrency-codemods async-arrow-task app/services/menu.js
Processing 1 files... 
Spawning 1 workers...
Sending 1 files to free worker...
All done. 
Results: 
0 errors
0 unmodified
0 skipped
1 ok
```

I would have expected `**/*.js` to pick this up? Or am I missing something here :sweat_smile: 

What did seem to work, but shouldn't be expected as far as I understand, is `npx machty-ember-concurrency-codemods async-arrow-task **/**/*.js`

**Comment by machty** [comment]
@mydea which shell are you using? bash, zsh, other?

**Comment by mydea** [comment]
I am using bash!

**Comment by machty** [comment]
Closing, see comment: https://github.com/machty/ember-concurrency/issues/484#issuecomment-1240655724

**Comment by mydea** [comment]
Hmm, that didn't do the trick for me - running:

```
npx machty-ember-concurrency-codemods async-arrow-task app/**/*.ts
```

Only migrates `app/*/*.ts` for me - so it will catch e.g. `app/components/my-thing.ts`, but not `app/components/my-thing/nested.ts` 

Basically, it seems to be interpreting `**` as `*`, as far as I can tell!

**Comment by mydea** [comment]
Ah, I figured it out. I have to put the glob in quotes, so:

```
npx machty-ember-concurrency-codemods async-arrow-task "app/**/*.ts"
```

Then it actually works as expected!
